// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "sosmed/features/comment/domain"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Create provides a mock function with given fields: newComment
func (_m *Service) Create(newComment domain.Core) (domain.Cores, error) {
	ret := _m.Called(newComment)

	var r0 domain.Cores
	if rf, ok := ret.Get(0).(func(domain.Core) domain.Cores); ok {
		r0 = rf(newComment)
	} else {
		r0 = ret.Get(0).(domain.Cores)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.Core) error); ok {
		r1 = rf(newComment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ID
func (_m *Service) Delete(ID int) error {
	ret := _m.Called(ID)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewService interface {
	mock.TestingT
	Cleanup(func())
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewService(t mockConstructorTestingTNewService) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
